# pack_mod_assets.ps1 — helpers for deploy.ps1 mod asset pipeline.
# Mod textures ship as PNG; the game loads them at runtime via Texture2D.FromStream.

function Get-ModAssetSources {
    param(
        [string]$ModSourcePath,
        [object]$Manifest
    )

    $files = @{}
    $assetsRoot = Join-Path $ModSourcePath 'assets'
    if (Test-Path $assetsRoot) {
        Get-ChildItem $assetsRoot -Recurse -File -Filter '*.png' | ForEach-Object {
            $baseName = [System.IO.Path]::GetFileNameWithoutExtension($_.Name)
            $files[$baseName] = $_
        }
    }

    if ($Manifest.assets) {
        foreach ($field in @('icons', 'textures')) {
            $list = $Manifest.assets.$field
            if (-not $list) { continue }
            foreach ($relPath in $list) {
                $fullPath = Join-Path $ModSourcePath ($relPath -replace '/', '\')
                if (-not (Test-Path $fullPath)) { continue }
                if ([System.IO.Path]::GetExtension($fullPath) -ne '.png') { continue }
                $baseName = [System.IO.Path]::GetFileNameWithoutExtension($fullPath)
                $files[$baseName] = Get-Item $fullPath
            }
        }
    }

    return $files.Values
}

function Invoke-ModAssetPipeline {
    param(
        [string]$RepoRoot,
        [array]$DiscoveredMods,
        [string]$StagingRoot
    )

    if (Test-Path $StagingRoot) {
        Remove-Item $StagingRoot -Recurse -Force
    }
    New-Item -ItemType Directory -Force -Path $StagingRoot | Out-Null

    $manifestLines = @()
    $pngCount = 0

    foreach ($mod in $DiscoveredMods) {
        $modId = $mod.Manifest.id
        $sources = Get-ModAssetSources -ModSourcePath $mod.SourcePath -Manifest $mod.Manifest

        foreach ($file in $sources) {
            $baseName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
            $logicalName = "$modId/$baseName"
            $contentPath = "ModAssets\\$modId\\$baseName"
            $pngRelativePath = "ModAssets\\$modId\\$baseName.png"
            $destDir = Join-Path $StagingRoot "ModAssets\$modId"
            $destPng = Join-Path $destDir "$baseName.png"

            New-Item -ItemType Directory -Force -Path $destDir | Out-Null
            Copy-Item $file.FullName $destPng -Force
            $pngCount++

            $manifestLines += "            AssetRegistry.Register(`"$logicalName`", `"$contentPath`", `"$pngRelativePath`");"
        }
    }

    return [PSCustomObject]@{
        ManifestLines = $manifestLines
        PngCount      = $pngCount
    }
}

function Write-GeneratedAssetManifest {
    param(
        [string]$TargetPath,
        [string[]]$RegisterLines
    )

    $lines = @()
    $lines += '// AUTO-GENERATED -- do not edit. Regenerated by deploy.ps1.'
    $lines += 'namespace DNA.CastleMinerZ.ModAPI.Internal'
    $lines += '{'
    $lines += '    public static class GeneratedAssetManifest'
    $lines += '    {'
    $lines += '        public static void Initialize()'
    $lines += '        {'

    if ($RegisterLines -and $RegisterLines.Count -gt 0) {
        $lines += $RegisterLines
    }

    $lines += '        }'
    $lines += '    }'
    $lines += '}'

    [System.IO.File]::WriteAllText($TargetPath, ($lines -join "`r`n"))
}
